### ISSUE TITLE
fatal error: rosabridge_msgs/Odometry.h: No such file or directory

### ISSUE THREAD

**Issue by AtharvaBhorpe** [ecostech/rosabridge#3]
Hi! I cloned your repository in a ROS Melodic workspace, and tried to "_catkin_make_" the workspace, but i got an error:

> /home/vm/URDFs/src/rosabridge/rosabridge_server/src/odom_proxy_node.cpp:2:10: fatal error: rosabridge_msgs/Odometry.h: No such file or directory
 #include "rosabridge_msgs/Odometry.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
rosabridge/rosabridge_server/CMakeFiles/rosabridge_server_odom_proxy_node.dir/build.make:62: recipe for target 'rosabridge/rosabridge_server/CMakeFiles/rosabridge_server_odom_proxy_node.dir/src/odom_proxy_node.cpp.o' failed
make[2]: *** [rosabridge/rosabridge_server/CMakeFiles/rosabridge_server_odom_proxy_node.dir/src/odom_proxy_node.cpp.o] Error 1
CMakeFiles/Makefile2:8693: recipe for target 'rosabridge/rosabridge_server/CMakeFiles/rosabridge_server_odom_proxy_node.dir/all' failed
make[1]: *** [rosabridge/rosabridge_server/CMakeFiles/rosabridge_server_odom_proxy_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/vm/URDFs/src/rosabridge/rosabridge_server/src/imu_proxy_node.cpp:2:10: fatal error: rosabridge_msgs/Imu.h: No such file or directory
 #include "rosabridge_msgs/Imu.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
rosabridge/rosabridge_server/CMakeFiles/rosabridge_server_imu_proxy_node.dir/build.make:62: recipe for target 'rosabridge/rosabridge_server/CMakeFiles/rosabridge_server_imu_proxy_node.dir/src/imu_proxy_node.cpp.o' failed
make[2]: *** [rosabridge/rosabridge_server/CMakeFiles/rosabridge_server_imu_proxy_node.dir/src/imu_proxy_node.cpp.o] Error 1
CMakeFiles/Makefile2:8656: recipe for target 'rosabridge/rosabridge_server/CMakeFiles/rosabridge_server_imu_proxy_node.dir/all' failed
make[1]: *** [rosabridge/rosabridge_server/CMakeFiles/rosabridge_server_imu_proxy_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j2 -l2" failed

Please let me know if the issue is from my side. Thank You!
![Screenshot from 2021-04-07 12-44-53](https://user-images.githubusercontent.com/62559868/113826266-93c9c400-979f-11eb-9ef3-ce3c94379543.png)

**Comment by attermann** [comment]
Hello. Seems the message generation dependencies were mistakenly left commented in a previous commit. I have re-enabled them (in ./rosabridge_server/CMakeLists.txt) so if you pull the latest and recompile you should be set. Thanks for the heads-up.

**Comment by AtharvaBhorpe** [comment]
IT COMPILES NOW!!! Thank You for such a quick response. This will really help me to optimize my code on Arduino. Really Great Work!!
